FROM siya/php7:latest
COPY env_dev /home/root/env_dev
COPY run.sh /home/root/run.sh
COPY php.ini /usr/local/etc/php/conf.d/
COPY sources.list /etc/apt/
COPY cronfile /etc/cron.d/cronfile
COPY site.conf /etc/nginx/sites-enabled/default
RUN mkdir -p /data/logs/ /data/app/project/
COPY supervisor.conf /etc/supervisor/conf.d/default.conf
ENV TZ=Asia/Shanghai
WORKDIR /data/app/project